### PR TITLE
UI: search improvements

### PR DESCRIPTION
**Pull request by juandiegocv27**
## Enhancements to Search UI

- **Query Lock:** Interaction is now disabled while a search query is pending, preventing duplicate queries and enhancing user experience.
  
- **UI Simplification:** Removed tabs from the search dropdown to simplify the interface, making the search results cleaner and more straightforward.

- **Search Bar Styling:** Updated the homepage search bar styling to align with the Optimistic Etherscan's layout, maintaining thematic consistency with the OP Mainnet Explorer.

image

**note:** update the code format with prettier in base with guidelines:

>  **pnpm prettier**

This update addresses various components of the search UI to improve functionality and aesthetics as outlined in **Issue #47**.

### CODE REVIEW

**Comment by juandiegocv27** [comment]
@saimeunt PR just fresh to merge!🚀🇨🇷

**Review by saimeunt — CHANGES_REQUESTED** [review]
@juandiegocv27 LGTM overall, please add the required dependency `cmdk` in package.json before we merge.

**Comment by juandiegocv27** [comment]
@saimeunt already add cmdk dependency🫡

**Comment by juandiegocv27** [comment]
@saimeunt I´ll continue trying to resolve the conflicts 🙌🏻

**Comment by juandiegocv27** [comment]
@saimeunt I resolved the confilcts

**Pull request closed without merging**
