### PR TITLE
Feat fetch latest l1->l2 transactions

### PR DESCRIPTION
**Pull request by danielcdz**
## Background
- Solves issue #11 
## Summary
- Retrieve the latest L1->L2 transactions fetching `SentMessage`/`SentMessageExtension1` and `RelayedMessage` events log from `L1CrossDomainMessenger` and `L2CrossDomainMessenger` contracts in Ethereum and Optimism.
- Remove hardcoded data.
- Filter the last 10 transactions.
## Visual result
- 
image

### CODE REVIEW

**Comment by saimeunt** [comment]
@danielcdz This is going in the right direction, note that you could use a slightly more friendly syntax to fetch logs from the contracts:

```
l1CrossDomainMessenger.getEvents.SentMessage(undefined, {
  fromBlock: l1FromBlock,
})
```

**Comment by danielcdz** [comment]
@saimeunt I added more commits, one is a refactor to the way of retrieving logs following your suggestions and separating them into one function for each event log, and the other is a WIP related to the re-computing of the `msgHash` and an attempt of search in the L2 logs, I want to know if I'm doing the recomputing right since I'm not getting any matching hash on the L2 logs, I'm following [this](https://github.com/ethereum-optimism/optimism/blob/7f403ea5f316a9085061bc63b6618afcdbca1278/packages/contracts-bedrock/src/libraries/Encoding.sol#L88) as reference

**Comment by saimeunt** [comment]
@danielcdz here is my understanding on why you're not getting any matches:

- Your compute `hexToBytes` function is unnecessary, you can pass the result of `encodeFunctionData` directly to `keccak256`.
- Your reconciliation of `SentMessage` and `SentMessageExtension1` is wrong, you should compare against both `transactionHash`es, not involving the `sender`.

Hope this helps!

**Comment by danielcdz** [comment]
> @danielcdz here is my understanding on why you're not getting any matches:
> 
> * Your compute `hexToBytes` function is unnecessary, you can pass the result of `encodeFunctionData` directly to `keccak256`.
> * Your reconciliation of `SentMessage` and `SentMessageExtension1` is wrong, you should compare against both `transactionHash`es, not involving the `sender`.
> 
> Hope this helps!

Thank you @saimeunt! 🫡 
Related to the 2nd point, what do I need to do is [this](https://github.com/walnuthq/op-scan/issues/11#:~:text=The%20correct%20way%20to%20perform%20the%20matching%20is%20to%20recompute%20the%20msgHash%20emitted%20in%20RelayedMessage%20from%20the%20arguments%20of%20SentMessage%20and%20SentMessageExtension1.) separately for SentMessage and SentMessageExtension1 and then compare the results with the transaction hash in the L2Events?

**Comment by saimeunt** [comment]
@danielcdz For each `SentMessage` event, you can easily track the accompanying `SentMessageExtension1` event by searching for a log with the same `transactionHash`. With these 2 events you will have all the data necessary to recompute the msgHash and find a matching `RelayedMessage` event on L2, which will give you the L2 `transactionHash`.

**Comment by danielcdz** [comment]
> @danielcdz For each `SentMessage` event, you can easily track the accompanying `SentMessageExtension1` event by searching for a log with the same `transactionHash`. With these 2 events you will have all the data necessary to recompute the msgHash and find a matching `RelayedMessage` event on L2, which will give you the L2 `transactionHash`.

Gotcha! ty @saimeunt !

**Comment by saimeunt** [comment]
@danielcdz You're almost there, a couple problems with your PR right now:

- Your output is different than Etherscan homepage, you need to get the very latest L1L2 transactions and at the moment you're missing the most recent ones.
- Remove the `fetch*` functions from `@/lib/utils.ts` because they're duplicated in your PR, probably because of a merge that happened at some point.
- Fix the conflict in `@/components/pages/home/latest-l1-l2-transactions.tsx` : don't touch this file it was already fine, you don't need to plug the L2 chain block explorer as it will always be the origin of this webapp.

**Comment by danielcdz** [comment]
> @danielcdz You're almost there, a couple problems with your PR right now:
> 
> * Your output is different than Etherscan homepage, you need to get the very latest L1L2 transactions and at the moment you're missing the most recent ones.
> * Remove the `fetch*` functions from `@/lib/utils.ts` because they're duplicated in your PR, probably because of a merge that happened at some point.
> * Fix the conflict in `@/components/pages/home/latest-l1-l2-transactions.tsx` : don't touch this file it was already fine, you don't need to plug the L2 chain block explorer as it will always be the origin of this webapp.

Ohh got it! I'm working on that!

**Comment by danielcdz** [comment]
@saimeunt I addressed your requests! Right now is matching perfectly the information with [Etherscan](https://optimistic.etherscan.io/txsEnqueued)

**Review by saimeunt — APPROVED** [review]
LGTM!

**Pull request merged**
